name: Checks

on: [push]

jobs:
  checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: make env-update

    - name: Style check (imports)
      run: make check-imports

    - name: Style check (code)
      run: make check-code

    - name: Run tests
      run: make tests

    - name: Coverage report
      run: make coverage

    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: os-${{ matrix.os }}, python${{ matrix.python-version }}
        env_vars: OS=${{ matrix.os }}, python=${{ matrix.python-version }}
        fail_ci_if_error: true
